services:
  - type: web
    name: speech-api
    runtime: python
    repo: https://github.com/YOUR_USERNAME/speech-pipeline
    branch: main
    buildCommand: "pip install -r requirements.txt"
    startCommand: "bash start.sh"
    plan: free
